logging:
  receivers:
    webapp-receiver:
      type: files
      include_paths:
        - /var/log/csye6225/application.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: @timestamp
      time_format: "%Y-%m-%dT%H:%M:%S.%L%z"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.level
  service:
    pipelines:
      default_pipeline:
        receivers: [webapp-receiver]
        processors: [my-app-processor, move_severity]
