name: Create Machine Image
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  PRODUCT_VERSION: "latest"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GCLOUD_CRED: ${{ secrets.GCP_CREDENTIALS }}
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: cloud_assignment
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check credentials
        run: echo $GCLOUD_CRED

      - name: Set up gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCLOUD_CRED }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Use gcloud CLI
        run: gcloud info

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run MySQL to create database
        run: mysql -h 127.0.0.1 -u root --password="" -e "CREATE DATABASE IF NOT EXISTS cloud_assignment"

      - name: Build package
        run: mvn clean package

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run Packer INIT
        run: packer init ./packer/compute-mi.pkr.hcl

      - name: Format Packer Template
        run: packer fmt ./packer/compute-mi.pkr.hcl

      - name: Validate Packer Template
        run: packer validate ./packer/compute-mi.pkr.hcl

      - name: Validate Packer Template
        run: packer build ./packer/compute-mi.pkr.hcl