name: Run Integration Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: cloud_assignment
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for SQL to start
        run: sleep 10s

      - name: Run MySQL to create database
        run: mysql -h 127.0.0.1 -u root --password="" -e "CREATE DATABASE IF NOT EXISTS cloud_assignment"

      - name: Install maven dependencies
        run: mvn clean install -DskipTests=true                     

      - name: Run application and test api's
        run: mvn test
        env:
          DATABASE_URL: mysql://root@localhost:3306/cloud_assignment