name: Run Packer Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  PRODUCT_VERSION: "latest"

jobs:
  packer-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Format Packer Template
        run: packer fmt ./packer/compute-mi.pkr.hcl

      - name: Validate Packer Template
        run: packer validate ./packer/compute-mi.pkr.hcl